# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e69f2f342f6bc0a26081e5d4cf8711053bf90c3ea33648d853e762e7c6cb303a9b970d09b1da7314b6b07cc8530bb9e7e439f74139b6c5c62f48bfebba8943f

test:
  secret_key_base: 6313e5a92c53a9ab6ae9c9e880e7963fca1920f50022885d7a31e902deb355999a4675a8b5b367eb331723261afdf65bddbd7fa43319224d481bb816851df11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
